# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4abd0ce3b33f75d5b66abf5a5c3057a7fc71f9cf90e23bd4f837488e50285dbee7202fcbe42467ff5c64ff4974f6444e6b1a7aaa2b80a674abc1e5b75a275c4

test:
  secret_key_base: 3cef90f11d54221fa1237061d7b225d41322d61f21a75729dcee321165f79e32007628f2c5f48983b482ff771fc240c28b8c39e34c65aa9b553755d8757b8ab2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
